apiVersion: v1
kind: Pod
metadata: 
  name: secretmount
spec: 
  containers: 
  - name: secretmount
    image: nginx:1.17.3
    env: 
    -  name: SECRET_USERNAME
       valueFrom:
         secretKeyRef: 
           name: firstsecret
           key: dbpass             # can be retrieved by running echo $SECRET_USERNAME inside container 
  restartPolicy: Never