apiVersion: v1
kind: Secret
metadata: 
  name: thirdsecret
type: Opaque
data: 
  username: ZGJhZG1pbg==            #base 64 encoding for 'dbadmin'
  password: bXlwYXNzMTIz            #base 64 encoding for 'mypass123' echo -n 'mypass123' | base64